language: python
python:
  - "3.14"
install:
  - pip install -r ./djangotutorial/requirements.txt
  - pip install coverage 'coveralls[yaml]' flake8 black
script: 
  - flake8 djangotutorial
  - black --check djangotutorial
  - coverage run -m pytest
after_success:
  - coveralls --verbose
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: mysite
  env: Mysite-env
  bucket: elasticbeanstalk-us-east-2-056230039457
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    branch: main
  edge: true # opt in to dpl v2
  